-- MOCA survey schema v1
-- Run this whole file in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.moca_survey_participants (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  student_id text not null unique,
  name text not null default '',
  department text not null default '',
  status text not null default 'in_progress' check (status in ('in_progress','completed')),
  primary_type text,
  secondary_type text,
  result jsonb,
  scores jsonb,
  part1_answers jsonb not null default '[]'::jsonb,
  part2_answers jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  offline_participated_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists moca_participants_owner_idx on public.moca_survey_participants(owner_id);
create index if not exists moca_participants_status_idx on public.moca_survey_participants(status);

create table if not exists public.moca_survey_responses (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.moca_survey_participants(id) on delete cascade,
  part smallint not null check (part in (1,2,3)),
  question_id text not null,
  behavior_stage text,
  selected_option text,
  selected_text text,
  linked_type text,
  option_position smallint,
  response_time_ms integer not null default 0,
  was_modified boolean not null default false,
  created_at timestamptz not null default now(),
  unique(participant_id, part, question_id)
);

create index if not exists moca_responses_participant_idx on public.moca_survey_responses(participant_id);
create index if not exists moca_responses_linked_type_idx on public.moca_survey_responses(linked_type);

create table if not exists public.moca_survey_drafts (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  student_id text not null,
  verified_user jsonb not null default '{}'::jsonb,
  current_page text not null default 'part1',
  part1_answers jsonb not null default '[]'::jsonb,
  part2_answers jsonb not null default '[]'::jsonb,
  comparison_state jsonb,
  compare_answers jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.moca_survey_participants enable row level security;
alter table public.moca_survey_responses enable row level security;
alter table public.moca_survey_drafts enable row level security;

-- Drafts belong only to the current anonymous Supabase user.
drop policy if exists "moca draft own select" on public.moca_survey_drafts;
create policy "moca draft own select" on public.moca_survey_drafts
for select to authenticated using ((select auth.uid()) = owner_id);

drop policy if exists "moca draft own insert" on public.moca_survey_drafts;
create policy "moca draft own insert" on public.moca_survey_drafts
for insert to authenticated with check ((select auth.uid()) = owner_id);

drop policy if exists "moca draft own update" on public.moca_survey_drafts;
create policy "moca draft own update" on public.moca_survey_drafts
for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);

-- Direct participant/response access is intentionally denied to clients.
-- All participant/result operations go through the RPC functions below.

create or replace function public.claim_moca_survey(
  p_student_id text,
  p_name text,
  p_department text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_row public.moca_survey_participants%rowtype;
begin
  if v_uid is null then raise exception 'authentication required'; end if;
  if nullif(trim(p_student_id), '') is null then raise exception 'student_id required'; end if;

  select * into v_row from public.moca_survey_participants where student_id = trim(p_student_id);

  if found then
    if v_row.status = 'completed' then
      return jsonb_build_object(
        'status','completed',
        'verifiedUser', jsonb_build_object('name',v_row.name,'studentId',v_row.student_id,'department',v_row.department),
        'result', v_row.result,
        'scores', v_row.scores,
        'part1Answers', v_row.part1_answers,
        'part2Answers', v_row.part2_answers,
        'completedAt', v_row.completed_at,
        'offlineParticipatedAt', v_row.offline_participated_at
      );
    end if;

    -- Same browser/session can resume. A stale in-progress claim can be reclaimed after 6 hours.
    if v_row.owner_id = v_uid or v_row.updated_at < now() - interval '6 hours' then
      update public.moca_survey_participants
      set owner_id=v_uid, name=trim(p_name), department=trim(p_department), updated_at=now()
      where id=v_row.id;
      return jsonb_build_object('status','claimed');
    end if;

    return jsonb_build_object('status','in_progress_elsewhere');
  end if;

  insert into public.moca_survey_participants(owner_id, student_id, name, department)
  values (v_uid, trim(p_student_id), trim(p_name), trim(p_department));
  return jsonb_build_object('status','claimed');
end;
$$;

create or replace function public.complete_moca_survey(
  p_student_id text,
  p_result jsonb,
  p_scores jsonb,
  p_part1_answers jsonb,
  p_part2_answers jsonb,
  p_responses jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_participant public.moca_survey_participants%rowtype;
  v_item jsonb;
begin
  if v_uid is null then raise exception 'authentication required'; end if;

  select * into v_participant
  from public.moca_survey_participants
  where student_id = trim(p_student_id)
  for update;

  if not found then raise exception 'survey claim not found'; end if;

  if v_participant.status = 'completed' then
    return jsonb_build_object('status','already_completed','result',v_participant.result,'completedAt',v_participant.completed_at);
  end if;

  if v_participant.owner_id <> v_uid then raise exception 'survey is owned by another session'; end if;

  update public.moca_survey_participants set
    status='completed',
    primary_type=p_result->>'primaryType',
    secondary_type=p_result->>'secondaryType',
    result=p_result,
    scores=p_scores,
    part1_answers=coalesce(p_part1_answers,'[]'::jsonb),
    part2_answers=coalesce(p_part2_answers,'[]'::jsonb),
    completed_at=coalesce(completed_at,now()),
    updated_at=now()
  where id=v_participant.id;

  delete from public.moca_survey_responses where participant_id=v_participant.id;
  for v_item in select value from jsonb_array_elements(coalesce(p_responses,'[]'::jsonb)) loop
    insert into public.moca_survey_responses(
      participant_id, part, question_id, behavior_stage, selected_option, selected_text,
      linked_type, option_position, response_time_ms, was_modified
    ) values (
      v_participant.id,
      coalesce((v_item->>'part')::smallint, 2),
      v_item->>'question_id',
      v_item->>'behavior_stage',
      v_item->>'selected_option',
      v_item->>'selected_text',
      v_item->>'linked_type',
      nullif(v_item->>'option_position','')::smallint,
      coalesce(nullif(v_item->>'response_time_ms','')::integer,0),
      coalesce((v_item->>'was_modified')::boolean,false)
    );
  end loop;

  delete from public.moca_survey_drafts where owner_id=v_uid;
  return jsonb_build_object('status','completed','completedAt',now());
end;
$$;

create or replace function public.mark_moca_offline_participation(p_student_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.moca_survey_participants%rowtype;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into v_row from public.moca_survey_participants where student_id=trim(p_student_id) for update;
  if not found or v_row.status <> 'completed' then return jsonb_build_object('status','not_completed'); end if;
  if v_row.offline_participated_at is not null then
    return jsonb_build_object('status','already_participated','offlineParticipatedAt',v_row.offline_participated_at);
  end if;
  update public.moca_survey_participants set offline_participated_at=now(), updated_at=now() where id=v_row.id;
  return jsonb_build_object('status','marked','offlineParticipatedAt',now());
end;
$$;

revoke all on function public.claim_moca_survey(text,text,text) from public;
revoke all on function public.complete_moca_survey(text,jsonb,jsonb,jsonb,jsonb,jsonb) from public;
revoke all on function public.mark_moca_offline_participation(text) from public;
grant execute on function public.claim_moca_survey(text,text,text) to authenticated;
grant execute on function public.complete_moca_survey(text,jsonb,jsonb,jsonb,jsonb,jsonb) to authenticated;
grant execute on function public.mark_moca_offline_participation(text) to authenticated;

grant select, insert, update on public.moca_survey_drafts to authenticated;
